version: "3.1"

services:
  scrapyd:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-scrapyd
    image: usydapeng/scrapyd:0.0.1
    restart: always
    ports:
      - 16800:16800
      - 16801:16801
      - 17905:7900
    volumes:
      - ./scrapyd-storage/dbs:/app/dbs
      - ./scrapyd-storage/logs:/app/logs
      - ./scrapyd-storage/gerapy:/app/gerapy
  scrapydweb:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-scrapydweb
    image: usydapeng/scrapydweb:0.0.1
    restart: always
    ports:
      - 15001:15001
    depends_on:
      - scrapyd
